[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[font]
size = 22.0

[font.bold]
family = "CartographCF Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "CartographCF Nerd Font"
style = "ExtraBold Italic"

[font.italic]
family = "CartographCF Nerd Font"
style = "Italic"

[font.normal]
family = "CartographCF Nerd Font"
style = "ExtraLight"

[font.offset]
x = 0
y = 1

[mouse]
hide_when_typing = true

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "Buttonless"
dynamic_title = true
dynamic_padding = true
opacity = 0.9
option_as_alt = "Both"
blur = true

[window.padding]
x = 5
y = 0
