[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[font]
size = 22.0

[font.bold]
family = "CartographCF Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "CartographCF Nerd Font"
style = "DemiBold Italic"

[font.italic]
family = "CartographCF Nerd Font"
style = "Italic"

[font.normal]
family = "CartographCF Nerd Font"
style = "Light"

[font.offset]
x = -1
y = 0

[mouse]
hide_when_typing = true


[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.9
option_as_alt = "Both"
blur = true

[window.padding]
x = 3
y = 0
