---
luarocks:
- luaformatter
npm:
- nvim
- bash-language-server
- vscode-langservers-extracted
- dockerfile-language-server-nodejs
- vscode-langservers-extracted
- typescript
- typescript-language-server
- vim-language-server
- '@rafaelrinaldi/hn-cli'
cask:
- ngrok
tap:
- jandedobbeleer/oh-my-posh
brew:
- terraform
- k9s
- ranger
- pwgen
- hashicorp/tap/terraform-ls
- efm-langserver
- luarocks
- bash
- oh-my-posh
- helm
- jo
- just
- lsd
- bat
- ctags
- fd
- fzf
- git
- hadolint
- jq
- pipx
- ripgrep
- shellcheck
- stow
- tldr
- tmux
- tree-sitter
- yarn
- zsh
- vivid
- ninja
repos:
- alexanderjeurissen/ranger_devicons
- elasticdog/transcrypt
- mbadolato/iterm2-color-schemes
- jan-warchol/selenized
- ansible/ansible-language-server
- sumneko/lua-language-server
- bashup/dotenv
- microsoft/vscode-node-debug2
- microsoft/vscode-chrome-debug
sgmlinks:
- src: elasticdog/transcrypt/transcrypt
  dest: ~/.local/bin/transcrypt
- src: ansible/ansible-language-server/bin/ansible-language-server
  dest: ~/.local/bin/ansible-language-server
- src: bashup/dotenv/dotenv
  dest: ~/.local/bin/dotenv
go:
- github.com/rakyll/gotest@latest
- mvdan.cc/sh/v3/cmd/shfmt@latest
- github.com/go-delve/delve/cmd/dlv@latest
