---
cargo:
- argc
pipx:
- diagrams
- httpie
- pgcli
- rich-cli
luarocks:
- luaformatter
npm:
- npm-groovy-lint
- pyright
- neovim
- bash-language-server
- vscode-langservers-extracted
- dockerfile-language-server-nodejs
- vscode-langservers-extracted
- typescript
- typescript-language-server
- vim-language-server
cask:
- ngrok
- homebrew/cask/basictex
tap:
- cantino/mcfly
- jandedobbeleer/oh-my-posh
brew:
- pgcli
- hidetatz/tap/kubecolor
- dasel
- kubectl
- docker
- colima
- git-filter-repo
- skhd
- sqlfluff
- kustomize
- pandoc
# Pandoc Dependencies
- librsvg
# Misc
- fx
- rust-analyzer
- coreutils
- graphviz
- git-delta
- cantino/mcfly/mcfly
- jless
- zk
- mongocli
- ffmpeg
- yamllint
- postgresql
- terraform
- k9s
- pwgen
- hashicorp/tap/terraform-ls
- luarocks
- bash
- oh-my-posh
- helm
- jo
- lsd
- bat
- fd
- fzf
- git
- hadolint
- jq
- pipx
- ripgrep
- shellcheck
- stow
- tldr
- tmux
- tree-sitter
- yarn
- zsh
- vivid
- ninja
repos:
- shaunsingh/SFMono-Nerd-Font-Ligaturized
- k0nserv/kitty-icon
- elasticdog/transcrypt
- mbadolato/iterm2-color-schemes
- jan-warchol/selenized
- ansible/ansible-language-server
- sumneko/lua-language-server
- bashup/dotenv
- microsoft/vscode-node-debug2
- microsoft/vscode-chrome-debug
symlinks:
- src: elasticdog/transcrypt/transcrypt
  dest: ~/.local/bin/transcrypt
- src: ansible/ansible-language-server/bin/ansible-language-server
  dest: ~/.local/bin/ansible-language-server
- src: bashup/dotenv/dotenv
  dest: ~/.local/bin/dotenv
go:
- github.com/hidetatz/kubecolor/kubecolor@latest
- github.com/rakyll/gotest@latest
- mvdan.cc/sh/v3/cmd/shfmt@latest
- github.com/go-delve/delve/cmd/dlv@latest
- github.com/ericchiang/pup
