console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  aws_yellow = '#FFA400'
  kubernetes_blue = '#7dcfff'
  node_green = '#6CA35E'
  tokyonight_blue = '#6d91de'
  tokyonight_gray = '#AFBAD4'
  tokyonight_green = '#73daca'
  tokyonight_magenta = '#ff007c'
  tokyonight_purple = '#9d7cd8'
  tokyonight_yellow = '#ffe873'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:tokyonight_magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground = ''
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}p:tokyonight_magenta{{end}}', '{{if eq .Code 0}}p:tokyonight_purple{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ if matchP "/branches/" .Path }}{{ .Path | replace "/branches/" " <#FFF>󱏒</> <p:tokyonight_blue>" }}</>{{ else }}{{ .Path }}{{ end }}'
    foreground = 'p:tokyonight_green'
    background = 'transparent'
    type = 'path'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    style = 'plain'
    template = '  {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <p:tokyonight_purple>{{ if gt .Behind 0 }}{{ end }}{{ if gt .Ahead 0 }}{{ end }}</>'
    foreground = '#ffffff'
    background = 'transparent'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true
      tag_icon = ' '

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .FormattedMs }}'
    foreground = 'p:tokyonight_yellow'
    background = 'transparent'
    type = 'executiontime'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '❯'
    foreground = ''
    background = 'transparent'
    type = 'text'
    foreground_templates = ['{{if gt .Code 0}}p:tokyonight_magenta{{end}}', '{{if eq .Code 0}}p:tokyonight_purple{{end}}']

[[tooltips]]
  style = 'plain'
  template = '  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
  foreground = 'p:node_green'
  powerline_symbol = ''
  background = ''
  type = 'node'
  tips = ['node', 'npm', 'ts-node']

[[tooltips]]
  style = 'plain'
  foreground = 'p:tokyonight_yellow'
  background = ''
  type = 'command'
  tips = ['python']

  [tooltips.properties]
    command = "if [ -n \"$VIRTUAL_ENV_PROMPT\" ]; then echo \" $VIRTUAL_ENV_PROMPT\"; elif [ -f './.python-version' ]; then echo  $(/bin/cat ./.python-version); fi"
    shell = 'zsh'

[[tooltips]]
  style = 'plain'
  foreground = 'p:aws_yellow'
  background = 'transparent'
  type = 'command'
  tips = ['aws']

  [tooltips.properties]
    command = 'if [[ -n $AWS_PROFILE ]]; then echo " $AWS_PROFILE ($AWS_REGION)" ; fi'
    shell = 'zsh'

[[tooltips]]
  style = 'plain'
  foreground = 'p:kubernetes_blue'
  background = ''
  type = 'command'
  tips = ['k', 'kubectl']

  [tooltips.properties]
    command = "if [[ -n \"$(rg \"current-context: .*$\" ~/.kube/config)\" ]]; then echo \" $(rg 'current-context: .*$' ~/.kube/config | sed -e 's|current-context: ||' | tr -d ' ')\" ; fi"
    shell = 'zsh'
