- name: Configure
  command:
    chdir: '{{ root }}/repos/sumneko/lua-language-server/3rd/luamake'
    cmd: 'compile/install.sh'

- name: Rebuild
  command:
    chdir: '{{ root }}/repos/sumneko/lua-language-server'
    cmd: './3rd/luamake/luamake rebuild'

- name: Stow lua-language-server binary
  command:
    chdir: '{{ root }}/repos/sumneko/lua-language-server'
    cmd: 'stow -t ~/.local/bin bin'

- name: Stow
  command:
    chdir: '{{ root }}/repos/sumneko/lua-language-server/3rd'
    cmd: stow -t ~/.local/bin --ignore='^((?!luamake).)*$' luamake


