#!/usr/bin/env bash

config=$(kubectl config get-contexts | awk '{print $2}' | tail -n '+2' | fzf-tmux -p 80%,40%)

if [ -z "$config" ]; then exit 0; fi

clear

hr.sh '─'

kubectl config use-context $config

dotenv -f ~/.config/ohmyposh/.env set OHMYPOSH_KUBERNETES_CONTEXT=" $config"

printf "\nUsing $config context\n"

hr.sh '─'
