#!/usr/bin/env bash

today=$(date +%Y-%m-%d)
now=$(date +%H:%M)
note="$HOME/.notes/quick/$today.norg"

if [ ! -f $note ]; then
  cat > $note <<EOF
@document.meta
  title: Quick Notes - $today
  description: Quick note generated by quicknote.sh
  author: Guzmán Monné
  categories: quicknote
  created: $today
  version: 1.0
@end

= TOC Table of Contents

* Quick Notes - $today

EOF
fi

nvim \
  -c "Neorg workspace quick" \
  -c "e $note" \
  -c "norm Go  ** $now" \
  -c "norm Go" \
  -c "norm zz"

