#!/usr/bin/env bash
# This script was generated by rargs 0.0.0 (https://rargs.cloudbridge.uy)
# Modifying it manually is not recommended

if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
  printf "bash version 4 or higher is required\n" >&2
  exit 1
fi

if [[ -n "${DEBUG:-}" ]]; then
  set -x
fi
set -e


normalize_input() {
  local arg flags

  while [[ $# -gt 0 ]]; do
    arg="$1"
    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
      flags="${BASH_REMATCH[1]}"
      for ((i = 0; i < ${#flags}; i++)); do
        input+=("-${flags:i:1}")
      done
    else
      input+=("$arg")
    fi

    shift
  done
}

inspect_args() {
  prefix="rargs_"
  args="$(set | grep ^$prefix || true)"
  if [[ -n "$args" ]]; then
    echo
    echo args:
    for var in $args; do
      echo "- $var" | sed 's/=/ = /g'
    done
  fi

  if ((${#deps[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
    echo
    echo deps:
    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
  fi

  if ((${#other_args[@]})); then
    echo
    echo other_args:
    echo "- \${other_args[*]} = ${other_args[*]}"
    for i in "${!other_args[@]}"; do
      echo "- \${other_args[$i]} = ${other_args[$i]}"
    done
  fi
}

version() {
  echo "0.1.0"
}
usage() {
  printf "Utility functions to work with SSH\n"
  printf "\n\033[4m%s\033[0m\n" "Usage:"
  printf "  ssh.sh [OPTIONS] [COMMAND] [COMMAND_OPTIONS]\n"
  printf "  ssh.sh -h|--help\n"
  printf "  ssh.sh -v|--version\n"
  printf "\n\033[4m%s\033[0m\n" "Commands:"
  cat <<EOF
  nvim .... Copy the local "nvim" configuration to a remote server using scp.
EOF
  printf "  [@default nvim]\n"

  printf "\n\033[4m%s\033[0m\n" "Options:"
  printf "  -h --help\n"
  printf "    Print help\n"
  printf "  -v --version\n"
  printf "    Print version\n"
}

parse_arguments() {
  while [[ $# -gt 0 ]]; do
    case "${1:-}" in
      -v|--version)
        version
        exit
        ;;
      -h|--help)
        usage
        exit
        ;;
      *)
        break
        ;;
    esac
  done
  action="${1:-}"

  case $action in
    nvim)
      action="nvim"
      input=("${input[@]:1}")
      ;;
    -h|--help)
      usage
      exit
      ;;
    "")
      action="nvim"
      ;;
    *)
      action="nvim"
      ;;
  esac
}
nvim_usage() {
  printf "Copy the local "nvim" configuration to a remote server using scp.\n"

  printf "\n\033[4m%s\033[0m\n" "Usage:"
  printf "  nvim [OPTIONS] [IP]\n"
  printf "  nvim -h|--help\n"
  printf "\n\033[4m%s\033[0m\n" "Arguments:"
  printf "  IP\n"
  printf "    The IP address of the remote server.\n"

  printf "\n\033[4m%s\033[0m\n" "Options:"
  printf "  -k --key [<KEY>]\n"
  printf "    The SSH key to use to connect to the server.\n"
  printf "  -u --user [<USER>]\n"
  printf "    The user to use to connect to the server.\n"
  printf "    [@default ec2-user]\n"
  printf "  -h --help\n"
  printf "    Print help\n"
}
parse_nvim_arguments() {
  while [[ $# -gt 0 ]]; do
    case "${1:-}" in
      -h|--help)
        nvim_usage
        exit
        ;;
      *)
        break
        ;;
    esac
  done

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      -k | --key)
        rargs_key="$2"
        shift 2
        ;;
      -u | --user)
        rargs_user="$2"
        shift 2
        ;;
      -?*)
        printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Invalid option: " "$key" >&2
        exit 1
        ;;
      *)
        if [[ -z "$rargs_ip" ]]; then
          rargs_ip=$key
          shift
        else
          printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Invalid argument: " "$key" >&2
          exit 1
        fi
        ;;
    esac
  done
}
# Copy the local "nvim" configuration to a remote server using scp.
nvim() {
  local rargs_key
  local rargs_user
  local rargs_ip
  # Parse command arguments
  parse_nvim_arguments "$@"

  
    
  if [[ -z "$rargs_user" ]]; then
    rargs_user="ec2-user"
  fi
    
  if [[ -n "$rargs_key" ]]; then
    key="-i $rargs_key"
  else
    key=""
  fi
  scp  -r  $key  ~/.config/nvim/*.vim  ${rargs_user}@${rargs_ip}:/home/ec2-user/.config/nvim
  scp  -r  $key  ~/.config/nvim/*.lua  ${rargs_user}@${rargs_ip}:/home/ec2-user/.config/nvim
  scp  -r  $key  ~/.config/nvim/lua/   ${rargs_user}@${rargs_ip}:/home/ec2-user/.config/nvim/lua
}

run() {
  declare -A deps=()
  declare -a input=()
  normalize_input "$@"
  parse_arguments "${input[@]}"
  # Call the right command action
  case "$action" in
    "nvim")
      nvim "${input[@]}"
      exit
      ;;
    "")
      nvim
      exit
      ;;
    
  esac
}

run "$@"
