---
- name: Install all `brew` dependencies.
  hosts: localhost
  connection: local
  vars_files:
    - '{{ root }}/requirements.yml'
  tasks:
    - name: Brew cask
      community.general.homebrew_cask:
        name: '{{ item }}'
      loop: '{{ cask }}'
    - name: Brew tap
      community.general.homebrew_tap:
        name: '{{ item }}'
      loop: '{{ tap }}'
    - name: Brew install
      community.general.homebrew:
        name: '{{ item }}'
        state: latest
      loop: '{{ brew }}'
    - name: Brew install nvim
      community.general.homebrew:
        name: nvim
        state: head

