---
- name: Setup new Development Environment
  hosts: localhost
  connection: local
  tasks:
    - role: gantsign.antigen
      users:
        - username: '{{ user }}'
          antigen_libraries:
            - name: oh-my-zsh

    - name: Set zsh as default shell
      user:
        name: '{{ user }}'
        shell: '/usr/bin/zsh'
        sudo: yes

    - name: Stow .config
      stow:
        state: present
        package: .config
        dir: '{{ root }}/.config'
        target: '"$HOME"/.config'

    - name: Stow dotfiles
      stow:
        state: present
        package: zshrc
        dir: '{{ root }}/dotfiles'
        target: '$HOME'

